### ISSUE TITLE
Latest Commit

### ISSUE THREAD

**Issue by NotLeakySus** [D3SOX/vencord-userplugins#11]
![image](https://github.com/D3SOX/vencord-userplugins/assets/58016298/44eff6a6-48f4-4f00-84a3-61db3ea10f8b)

**Comment by NotLeakySus** [comment]
heres the CMD Error when trying to build 

> vencord@1.7.1 build C:\Users\lekle\Desktop\Vencord
> node --require=./scripts/suppressExperimentalWarnings.js scripts/build/build.mjs

X [ERRORX X X [[]X ERRORERROR[ [Expected value for define "IS_WEB" to be a string, got boolean instead]ERRORX ]ERROR

    C:\Users\lekle\node_modules\esbuild\lib\main.js:300:10:
 ][ ]      300 │     throw Expected value for define "IS_WEB" to be a string, got boolean instead ERRORExpected value for define "IS_WEB" to be a string, got boolean instead

    C:\Users\lekle\node_modules\esbuild\lib\main.js:300:10:
new Error(`Expected value for ${what}${key !== void 0 ? " " + quote(key) : ""} to be a string,...
          ╵           ]

    C:\Users\lekle\node_modules\esbuild\lib\main.js:300:10:
Expected value for define "IS_WEB" to be a string, got boolean insteadExpected value for define "IS_WEB" to be a string, got boolean instead      300 │     throw ^       300 │     throw

    C:\Users\lekle\node_modules\esbuild\lib\main.js:300:10:


    C:\Users\lekle\node_modules\esbuild\lib\main.js:300:10:


    at validateStringValue (C:\Users\lekle\node_modules\esbuild\lib\main.js:300:11)
    at pushCommonFlags (C:\Users\lekle\node_modules\esbuild\lib\main.js:400:37)
    at flagsForBuildOptions (C:\Users\lekle\node_modules\esbuild\lib\main.js:434:3)
    at buildOrContextContinue (C:\Users\lekle\node_modules\esbuild\lib\main.js:1020:9)
    at C:\Users\lekle\node_modules\esbuild\lib\main.js:994:11

Expected value for define "IS_WEB" to be a string, got boolean instead      300 │     throw new Error(`Expected value for ${what}${key !== void 0 ? " " + quote(key) : ""} to be a string,...
          ╵           new Error(`Expected value for ${what}${key !== void 0 ? " " + quote(key) : ""} to be a string,...
          ╵           1 error


    C:\Users\lekle\node_modules\esbuild\lib\main.js:300:10:
      300 │     throw ^new Error(`Expected value for ${what}${key !== void 0 ? " " + quote(key) : ""} to be a string,...
          ╵

    at validateStringValue (C:\Users\lekle\node_modules\esbuild\lib\main.js:300:11)
    at pushCommonFlags (C:\Users\lekle\node_modules\esbuild\lib\main.js:400:37)
    at flagsForBuildOptions (C:\Users\lekle\node_modules\esbuild\lib\main.js:434:3)
    at buildOrContextContinue (C:\Users\lekle\node_modules\esbuild\lib\main.js:1020:9)
    at C:\Users\lekle\node_modules\esbuild\lib\main.js:994:11

1 error
      300 │     throw ^^new Error(`Expected value for ${what}${key !== void 0 ? " " + quote(key) : ""} to be a string,...
          ╵

    at validateStringValue (C:\Users\lekle\node_modules\esbuild\lib\main.js:300:11)
    at pushCommonFlags (C:\Users\lekle\node_modules\esbuild\lib\main.js:400:37)
    at flagsForBuildOptions (C:\Users\lekle\node_modules\esbuild\lib\main.js:434:3)
    at buildOrContextContinue (C:\Users\lekle\node_modules\esbuild\lib\main.js:1020:9)
    at C:\Users\lekle\node_modules\esbuild\lib\main.js:994:11

1 error
^new Error(`Expected value for ${what}${key !== void 0 ? " " + quote(key) : ""} to be a string,...
          ╵

    at validateStringValue (C:\Users\lekle\node_modules\esbuild\lib\main.js:300:11)
    at pushCommonFlags (C:\Users\lekle\node_modules\esbuild\lib\main.js:400:37)
    at flagsForBuildOptions (C:\Users\lekle\node_modules\esbuild\lib\main.js:434:3)
    at buildOrContextContinue (C:\Users\lekle\node_modules\esbuild\lib\main.js:1020:9)
    at C:\Users\lekle\node_modules\esbuild\lib\main.js:994:11

1 error
^

    at validateStringValue (C:\Users\lekle\node_modules\esbuild\lib\main.js:300:11)
    at pushCommonFlags (C:\Users\lekle\node_modules\esbuild\lib\main.js:400:37)
    at flagsForBuildOptions (C:\Users\lekle\node_modules\esbuild\lib\main.js:434:3)
    at buildOrContextContinue (C:\Users\lekle\node_modules\esbuild\lib\main.js:1020:9)
    at C:\Users\lekle\node_modules\esbuild\lib\main.js:994:11

1 error


    at validateStringValue (C:\Users\lekle\node_modules\esbuild\lib\main.js:300:11)
    at pushCommonFlags (C:\Users\lekle\node_modules\esbuild\lib\main.js:400:37)
    at flagsForBuildOptions (C:\Users\lekle\node_modules\esbuild\lib\main.js:434:3)
    at buildOrContextContinue (C:\Users\lekle\node_modules\esbuild\lib\main.js:1020:9)
    at C:\Users\lekle\node_modules\esbuild\lib\main.js:994:11

1 error
Build failed
Build failed with 1 error:
C:\Users\lekle\node_modules\esbuild\lib\main.js:300:10: ERROR: Expected value for define "IS_WEB" to be a string, got boolean instead
 ELIFECYCLE  Command failed with exit code 1.

**Comment by D3SOX** [comment]
Are you sure it only happens when my repo is installed?

**Comment by NotLeakySus** [comment]
Rebuilding the dev build fixed it no worries now should've rebuilt before issuing sorry
